- package-lock.json
- package.json
- src/components/CustomChallenge/CustomCompleted.js
- src/utils/GetPercent.js
- src/views/Challenge.js
1、challenge页添加：切换题目时回到顶部
2、修复浮点数计算精度问题
> fix: 修复浮点数计算精度问题

- src/components/Cert/Nfts.js
- src/components/Cert/User.js
- src/hooks/useAccountInit.js
- src/views/Cert.js
- src/views/Search.js
> en: 调整nft获取顺序

- src/views/Challenge.js
> fix: challenge index error

- src/App.js
- src/assets/styles/component-style/challenge.scss
- src/components/BeforeRouterEnter/index.js
- src/components/CustomChallenge/CustomCompleted.js
- src/components/CustomChallenge/CustomDiscord.js
- src/containers/DefaultLayout.js
- src/redux/CustomSigner.js
- src/views/Claim.js
- src/views/Search.js
1、过滤claim页面discord无效验证请求
2、claim页添加loading效果
3、CustomSigner组件添加未链接钱包不拦截
> fix: claim页过滤错误请求

- src/request/index.js
- src/request/nft.js
1、修复response内data为空时，拦截器无法获取到data的错误
> fix: interceptors error

- src/assets/styles/component-style/question.scss
- src/assets/styles/mobile/view-style/challenge.scss
- src/assets/styles/view-style/challenge.scss
- src/components/CustomChallenge/CustomInput.js
- src/components/CustomItem/CustomQuestion.js
- src/components/Publish/CustomForm.js
- src/utils/getMetadata.js
- src/views/Challenge/index.js
- src/views/User/index.js
1、修复<preview>解析错误
2、修复<publish>预处理错误
3、<publish>题目展示调整
4、<challenge>h4样式修改
> chore: update style

- src/request/ipfs.js
> fix: ipfs path error

- src/views/Lesson.js
https://github.com/decert-me/website/issues/142
> fix: 优化教程列表加载速度

- src/App.js
- src/components/CustomModal/ModalConnect.js
- src/containers/AppHeader.js
- src/redux/CustomSigner.js
1、walletconnect 切换至v2
2、修复头部导航栏刷新丢失头像
> feat: walletconnect upgrade v2

- src/assets/styles/component-style/user/challenge.scss
- src/assets/styles/mobile/component-style/user/challengeItem.scss
- src/assets/styles/mobile/view-style/question.scss
- src/assets/styles/view-style/question.scss
- src/components/BeforeRouterEnter/index.js
> chore: 挑战描述样式

- src/views/Lesson.js
测试数据
```
[
{
"repoUrl": "https://github.com/decert-me/blockchain-basic",
"label": "区块链基础",
"startPage": "start",
"catalogueName": "blockchain-basic",
"docType": "docusaurus",
"img": "https://ipfs.decert.me/images/blockchain-basic.png",
"desc": "区块链是一项令人兴奋且在快速发展的技术，你也许看到过这些频繁在社交媒体、新闻频道上冒出的新名词：智能合约、代币（通证）、Web3、DeFi、DAO 组织。 如果你还不是很明白他们的意思，这份免费区块链基础教程就是为你（小白们）准备的。"
},
{
"repoUrl": "https://github.com/decert-me/learnsolidity",
"label": "学习 Solidity",
"startPage": "intro",
"catalogueName": "solidity",
"img": "https://ipfs.decert.me/images/learn-solidity.png",
"desc": "Solidity是一种专门为以太坊平台设计的编程语言，它是EVM智能合约的核心，是区块链开发人员必须掌握的一项技能。",
"docType": "docusaurus"
},
{
"repoUrl": "https://github.com/SixdegreeLab/MasteringChainAnalytics",
"label": "成为链上数据分析师",
"startPage": "README",
"catalogueName": …
```
> en: 添加readme起始页适配

- src/assets/styles/container.scss
- src/assets/styles/mobile/container.scss
- src/containers/AppFooter.js
- src/views/Cert.js
> feat: dune链接添加

- src/assets/locales/en-US/public.json
- src/assets/locales/zh-CN/public.json
- src/assets/styles/mobile/view-style/cert.scss
- src/assets/styles/view-style/lesson.scss
- src/request/api/public.js
- src/views/Lesson.js
> feat: 教程列表进度展示

- src/components/CustomChallenge/CustomCode.js
- src/components/CustomModal/ModalAnswers.js
- src/hooks/usePublish.js
- src/views/Challenge/index.js
- src/views/Index.js
- src/views/User/edit.js
- src/views/User/index.js
1、[user页列表请求多次](https://github.com/decert-me/website/commit/9dc279f7a6a8e30ce9358e61508e134429d47062)
2、[答题时有等待返回值的编程题时（点击下一题），答了单选或者多选题，当编程题的答案返回后选择题答案会丢失](https://github.com/decert-me/website/issues/189)
3、[创建、修改挑战跳转](https://github.com/decert-me/website/commit/1e3eee4f99ea37cf233d27cd00a862b8b0dbecff)
4、[challenge answers显示错误](https://github.com/decert-me/website/commit/ce0a5a8acd6b14ec9907037ad15f58540d634420)
5、[user修改成功后返回地址错误](https://github.com/decert-me/website/commit/3b4d8517b06d479ebc1079629d10b33b966264ec)
> chore: fix

- src/components/CustomChallenge/CustomClaim.js
- src/views/Lesson.js
1、[claim页分享、领取按钮添加锁](https://github.com/decert-me/website/commit/fd27f1d149795d2d60fbafc856857dfc5902a600)
2、[修复教程列表学习进度显示NaN](https://github.com/decert-me/website/commit/5450133d40a0b69237b591da2da974c37206273e)
3、[教程列表图片比例变动](https://github.com/decert-me/website/commit/b0e7c4c0081313bbcaf097a32b565405a6c2addb)
> chore: 教程列表显示

- src/App.js
- src/utils/GetSign.js
- src/utils/redux.js
- src/views/Explore.js
1、walletconnect初始不加载。
2、无限滚动分页加锁。
3、签名前清空缓存。
> hotfix：storage错误

- src/components/CustomModal/ModalAddCodeQuestion.js
- src/components/Publish/CustomCase.js
> hotfix: 删除测试用例显示错误

- src/views/Rating/modal.js
> hotfix: rating-modal

- src/views/Rating/index.js
fix: [#432](https://github.com/decert-me/website/issues/432)
> chore: rating-modal maskClosable

- src/views/Challenge/index.js
fix: [#26](https://github.com/decert-me/admin/issues/26)
> hotfix: annotation

- src/assets/locales/en-US/profile.json
- src/assets/locales/zh-CN/profile.json
- src/request/api/public.js
- src/views/Callback.js
- src/views/Challenge/index.js
- src/views/User/bindDiscordBtn.js
- src/views/User/bindEmailBtn.js
- src/views/User/bindGithubBtn.js
- src/views/User/rebindModal.js
- src/views/User/styles/component.scss
fix: [#26](https://github.com/decert-me/admin/issues/26)
feat: [#428](https://github.com/decert-me/website/issues/428)
> chore: fix-annotation && add-resubmit

- src/components/User/ChallengeItem.js
- src/views/Publish/index.js
> feat: modify claimed challenge
